// branchJSON.js
import centralIMG from '../assets/centralMG.png';

const branches = [
  { name: "Sucursal 1", adress: "Av. O'higgins 2713", adressImg: centralIMG, adressLink: "https://goo.gl/maps/U4ucQXjzRY3eZ32Q9"},
  { name: "Sucursal 2", adress: "Ricardo Lopez Cabrera" },
  { name: "Sucursal 3", adress: "Celso Barrios" },
  { name: "Sucursal 4", adress: "Av. O'higgins 2713" },
];
export default branches;
