import centralIMG from '../assets/centralMG.png'
import lilianMolina from '../assets/lilianMolina.png'
import lopezCabrera from '../assets/lopezCabrera.png'
import celsoBarrios from '../assets/celsoBarrios.png'


const branches = [
  { name: "Sucursal 1", adress: "Av. O'higgins 2713", adressImg: centralIMG , adressLink: "https://goo.gl/maps/U4ucQXjzRY3eZ32Q9"},
  { name: "Sucursal 2", adress: "Ricardo Lopez Cabrera 2632", adressImg: lopezCabrera , adressLink: "https://goo.gl/maps/nY5vnxpXkRTY4Jry6" },
  { name: "Sucursal 3", adress: "Celso Barrios 2491", adressImg: celsoBarrios, adressLink: "https://goo.gl/maps/m68j3CWBgxiFQ1Y17" },
  { name: "Sucursal 4", adress: "Lilian Molina 2791", adressImg: lilianMolina , adressLink: "https://goo.gl/maps/LPJadvoFs8HmDnfa9" },
];
export default branches;
