import desayuno from '../assets/desayuno.png';
import lilianMolina from "../assets/lilianMolina.png";
import lopezCabrera from "../assets/lopezCabrera.png";
import celsoBarrios from "../assets/celsoBarrios.png";

const products = [
  {
    name: 'Desayuno',
    Img: desayuno,
  },
  {
    name: "Sucursal 2",
    Img: lopezCabrera,
  },
  {
    name: "Sucursal 3",
    Img: celsoBarrios,
  },
  {
    name: "Sucursal 4",
    Img: lilianMolina,
  },
];
export default products;
