// import desayuno from '../assets/desayuno.png';
import palmeritas from "../assets/palmeritas.png";
import alfajorNegro from "../assets/alfajorNegro.png";
import pastaFrola from "../assets/pastaFrola.png";

const products = [
  // {
  //   name: 'Desayuno',
  //   Img: desayuno,
  // },
  {
    name: "pastaFrola",
    Img: pastaFrola,
  },
  {
    name: "alfajorNegro",
    Img: alfajorNegro,
  },
  {
    name: "palmeritas",
    Img:palmeritas,
  },
];
export default products;
