import palmeritas from "../assets/palmeritas.png";
import alfajorNegro from "../assets/alfajorNegro.png";
import pastaFrola from "../assets/pastaFrola.png";
import alfajoresByN from "../assets/alfajoresByN.png";
import alfajoreMaicena from "../assets/alfajorMaicena.png";
import biscocosMiel from "../assets/biscochosMiel.png";
import cañoncitos from "../assets/cañoncitos.png";
import merenguitos from "../assets/merenguitos.png";
import milHojas from "../assets/milHojas.png";
import ojosBuey from "../assets/ojosBuey.png";
import panCasero from "../assets/panCasero.png";
import panDulce from "../assets/panDulce.png";
import roscas from "../assets/roscas.png";

const products = [
  {
    name: "alfajoreMaicena",
    Img: alfajoreMaicena,
  },
  {
    name: "cañoncitos",
    Img: cañoncitos,
  },
  {
    name: "biscocosMiel",
    Img: biscocosMiel,
  },
  {
    name: "merenguitos",
    Img: merenguitos,
  },
  {
    name: "milHojas",
    Img: milHojas,
  },
  {
    name: "ojosBuey",
    Img: ojosBuey,
  },
  {
    name: "alfajoresByN",
    Img: alfajoresByN,
  },
  {
    name: "panCasero",
    Img: panCasero,
  },
  {
    name: "panDulce",
    Img: panDulce,
  },
  {
    name: "roscas",
    Img: roscas,
  },
  {
    name: "pastaFrola",
    Img: pastaFrola,
  },
  {
    name: "alfajorNegro",
    Img: alfajorNegro,
  },
  {
    name: "palmeritas",
    Img: palmeritas,
  },
];
export default products;
