import palmeritas from "../assets/palmeritas.png";
import alfajorNegro from "../assets/alfajorNegro.png";
import pastaFrola from "../assets/pastaFrola.png";
import alfajoresByN from "../assets/alfajoresByN.png";
import alfajoreMaicena from "../assets/alfajorMaicena.png";
import biscocosMiel from "../assets/biscochosMiel.png";
import cañoncitos from "../assets/cañoncitos.png";
import merenguitos from "../assets/merenguitos.png";
import milHojas from "../assets/milHojas.png";
import ojosBuey from "../assets/ojosBuey.png";
import panCasero from "../assets/panCasero.png";
import panDulce from "../assets/panDulce.png";
import roscas from "../assets/roscas.png";

const products = [
  {
    name: "Alfajor de Maicena",
    Img: alfajoreMaicena,
  },
  {
    name: "Cañoncitos de Dulce de Leche",
    Img: cañoncitos,
  },
  {
    name: "Biscochos Miel",
    Img: biscocosMiel,
  },
  {
    name: "Merenguitos",
    Img: merenguitos,
  },
  {
    name: "Mil Hojas",
    Img: milHojas,
  },
  {
    name: "Ojos de Buey",
    Img: ojosBuey,
  },
  {
    name: "Alfajores ",
    Img: alfajoresByN,
  },
  {
    name: "Pan Casero",
    Img: panCasero,
  },
  {
    name: "Pan Dulce",
    Img: panDulce,
  },
  {
    name: "Roscas",
    Img: roscas,
  },
  {
    name: "Pasta Frola",
    Img: pastaFrola,
  },
  {
    name: "Alfajor Negro",
    Img: alfajorNegro,
  },
  {
    name: "Palmeritas",
    Img: palmeritas,
  },
];
export default products;
